import { StyleSheet } from "react-native";

export const colors = {
  background: "#090a0c",
  surface: "#17181b",
  surfaceElevated: "#1c1d21",
  border: "#3a3d42",
  borderActive: "#ff3b4f",
  accent: "#ff3b4f",
  accentSoft: "#43151f",
  text: "#f1f1f2",
  textSecondary: "#a5a7ab",
  textMuted: "#70809b",
  textInverted: "#16090b",
  green: "#34d399",
  amber: "#fbbf24",
  blue: "#60a5fa",
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

export const typography = {
  eyebrow: {
    fontSize: 11,
    fontWeight: "800" as const,
    letterSpacing: 1.5,
    color: colors.accent,
  },
  title: { fontSize: 28, fontWeight: "800" as const, color: colors.text },
  section: { fontSize: 17, fontWeight: "800" as const, color: colors.text },
  body: { fontSize: 15, color: colors.text, lineHeight: 21 },
  meta: {
    fontSize: 10,
    fontWeight: "800" as const,
    letterSpacing: 1,
    color: colors.textSecondary,
  },
  message: { fontSize: 12, color: colors.textSecondary },
  input: { fontSize: 15, color: colors.text },
  button: { fontSize: 14, fontWeight: "800" as const },
  smallAction: { fontSize: 11, fontWeight: "800" as const },
  settingsLabel: {
    fontSize: 14,
    fontWeight: "700" as const,
    color: colors.text,
  },
};

export const sharedStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { gap: 18, padding: 22, paddingBottom: 40 },
  section: { ...typography.section, marginTop: 4 },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  input: {
    backgroundColor: "#0e0f12",
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.text,
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primary: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderRadius: 12,
    padding: 14,
  },
  primaryText: { ...typography.button, color: colors.textInverted },
  secondary: {
    alignItems: "center",
    borderColor: colors.accent,
    borderRadius: 12,
    borderWidth: 1,
    padding: 13,
  },
  secondaryText: { ...typography.button, color: colors.accent },
  message: { ...typography.message },
  toggleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  empty: {
    borderColor: colors.border,
    borderRadius: 18,
    borderStyle: "dashed",
    borderWidth: 1,
    padding: 20,
  },
  emptyTitle: { ...typography.body, fontWeight: "800", color: colors.text },
  emptyCopy: { ...typography.message, lineHeight: 19, marginTop: 5 },
  mission: {
    alignItems: "flex-start",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    padding: 15,
  },
  missionDot: {
    backgroundColor: colors.accent,
    borderRadius: 8,
    height: 8,
    marginTop: 5,
    width: 8,
  },
  missionBody: { flex: 1 },
  missionText: { ...typography.body },
  missionMeta: { ...typography.meta, marginTop: 7 },
  agentRow: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingVertical: 10,
  },
  agentMode: { ...typography.meta, color: colors.accent },
  actionRow: { flexDirection: "row", gap: 8, marginTop: 10 },
  smallAction: {
    borderColor: colors.accent,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  smallActionText: { ...typography.smallAction, color: colors.accent },
  selectedAction: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  settingsMenu: { gap: 8, marginTop: 12 },
  settingsMenuItem: {
    alignItems: "center",
    backgroundColor: "#15171b",
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  settingsMenuItemActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  settingsMenuLabel: { ...typography.settingsLabel },
  settingsMenuChevron: { color: colors.accent, fontSize: 24, lineHeight: 24 },
  scopeChip: {
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 6,
    paddingVertical: 7,
  },
  scopeChipActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  count: { color: colors.accent, fontSize: 14, fontWeight: "800" },
  sectionRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  hero: {
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    padding: 22,
  },
  heroKicker: { ...typography.eyebrow, color: "#c7c9cf", letterSpacing: 1.4 },
  heroTitle: {
    ...typography.title,
    fontSize: 30,
    color: "#ffffff",
    marginTop: 10,
  },
  heroCopy: { color: "#a5a7ab", fontSize: 15, lineHeight: 22, marginTop: 10 },
  header: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  eyebrow: { ...typography.eyebrow },
  status: { ...typography.eyebrow, marginTop: 8, letterSpacing: 1.2 },
  projectCard: {
    backgroundColor: "#121316",
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  checkRow: {
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    paddingVertical: 5,
  },
  tabBar: {
    backgroundColor: colors.surface,
    borderTopColor: colors.border,
    borderTopWidth: 1,
    paddingBottom: 8,
  },
  tabItem: {
    alignItems: "center",
    flex: 1,
    paddingVertical: 8,
  },
  tabLabel: { fontSize: 10, fontWeight: "700", letterSpacing: 0.5 },
  tabLabelActive: { color: colors.accent },
  tabLabelInactive: { color: colors.textMuted },
});

export const chatStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  messagesContainer: { flex: 1, padding: spacing.lg },
  messageWrapper: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  messageBubble: {
    maxWidth: "80%",
    padding: spacing.md,
    borderRadius: 16,
  },
  userBubble: {
    backgroundColor: "#1e3a5f",
    borderColor: colors.blue,
    borderWidth: 1,
    alignSelf: "flex-end",
  },
  agentBubble: {
    backgroundColor: "#2d1519",
    borderColor: colors.accent,
    borderWidth: 1,
    alignSelf: "flex-start",
  },
  messageText: { ...typography.body },
  messageTime: { fontSize: 10, color: colors.textMuted, marginTop: 4 },
  composerContainer: {
    padding: spacing.lg,
    borderTopColor: colors.border,
    borderTopWidth: 1,
    backgroundColor: colors.surface,
  },
  composerRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: spacing.sm,
  },
  composerInput: {
    flex: 1,
    backgroundColor: "#0e0f12",
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    color: colors.text,
    fontSize: 16,
    lineHeight: 22,
    minHeight: 48,
    maxHeight: 140,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  welcomeContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.xxl,
  },
  welcomeIcon: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.lg,
  },
  welcomeTitle: {
    ...typography.title,
    fontSize: 24,
    textAlign: "center",
    marginBottom: spacing.sm,
  },
  welcomeSubtitle: {
    ...typography.message,
    textAlign: "center",
    marginBottom: spacing.xxl,
    maxWidth: 320,
  },
  suggestionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    justifyContent: "center",
  },
  suggestionCard: {
    width: 150,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
  },
  suggestionIcon: { fontSize: 24, marginBottom: spacing.xs },
  suggestionTitle: { ...typography.body, fontWeight: "700", marginBottom: 2 },
  suggestionDesc: { fontSize: 11, color: colors.textMuted },
});
